trigger:
  - master
  - release/*
  - feature/*
  - ci/*

jobs:
  - job: Windows
    pool:
      vmImage: "windows-latest"
    steps:
      - task: Gradle@2
        displayName: "Gradle Assemble"
        inputs:
          workingDirectory: ""
          gradleWrapperFile: "gradlew"
          javaHomeOption: "JDKVersion"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          publishJUnitResults: false
          testResultsFiles: "**/TEST-*.xml"
          tasks: "assemble"
      - task: Gradle@2
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        displayName: "Collect Jars"
        inputs:
          workingDirectory: ""
          gradleWrapperFile: "gradlew"
          javaHomeOption: "JDKVersion"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          publishJUnitResults: false
          tasks: "collectJars"
      - task: ArchiveFiles@2
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)/build/kb.abc/collected/"
          includeRootFolder: true
          archiveType: "tar"
          tarCompression: "gz"
          archiveFile: "$(System.DefaultWorkingDirectory)/windows-$(Build.BuildNumber).tar.gz"
      - task: PublishPipelineArtifact@1
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          path: "$(System.DefaultWorkingDirectory)/windows-$(Build.BuildNumber).tar.gz"
          artifact: "windows"
  - job: Linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: Gradle@2
        displayName: "Gradle Assemble"
        inputs:
          workingDirectory: ""
          gradleWrapperFile: "gradlew"
          javaHomeOption: "JDKVersion"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          publishJUnitResults: false
          testResultsFiles: "**/TEST-*.xml"
          tasks: "assemble"
      - task: Gradle@2
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        displayName: "Collect Jars"
        inputs:
          workingDirectory: ""
          gradleWrapperFile: "gradlew"
          javaHomeOption: "JDKVersion"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          publishJUnitResults: false
          tasks: "collectJars"
      - task: ArchiveFiles@2
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)/build/kb.abc/collected/"
          includeRootFolder: true
          archiveType: "tar"
          tarCompression: "gz"
          archiveFile: "$(System.DefaultWorkingDirectory)/ubuntu-$(Build.BuildNumber).tar.gz"
      - task: PublishPipelineArtifact@1
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          path: "$(System.DefaultWorkingDirectory)/ubuntu-$(Build.BuildNumber).tar.gz"
          artifact: "ubuntu"
  - job: macOS
    pool:
      vmImage: "macOS-latest"
    steps:
      - task: Gradle@2
        displayName: "Gradle Assemble"
        inputs:
          workingDirectory: ""
          gradleWrapperFile: "gradlew"
          javaHomeOption: "JDKVersion"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          publishJUnitResults: false
          testResultsFiles: "**/TEST-*.xml"
          tasks: "assemble"
      - task: Gradle@2
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        displayName: "Collect Jars"
        inputs:
          workingDirectory: ""
          gradleWrapperFile: "gradlew"
          javaHomeOption: "JDKVersion"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          publishJUnitResults: false
          tasks: "collectJars"
      - task: ArchiveFiles@2
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)/build/kb.abc/collected/"
          includeRootFolder: true
          archiveType: "tar"
          tarCompression: "gz"
          archiveFile: "$(System.DefaultWorkingDirectory)/macOS-$(Build.BuildNumber).tar.gz"
      - task: PublishPipelineArtifact@1
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          path: "$(System.DefaultWorkingDirectory)/macOS-$(Build.BuildNumber).tar.gz"
          artifact: "macOS"