jobs:
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
      - script: echo hello from Windows
      - powershell: |
          mkdir build
          $ProgressPreference = 'SilentlyContinue'
          wget "https://download.java.net/java/GA/jdk12.0.2/e482c34c86bd4bf8b56c0b35558996b9/10/GPL/openjdk-12.0.2_windows-x64_bin.zip" -O "build\jdk.zip"
        displayName: 'Download JDK'
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: "12"
          jdkSourceOption: localDirectory
          jdkFile: 'build/jdk.zip'
          jdkDestinationDirectory: 'build/jdk_inst'
          jdkArchitectureOption: x64
      - task: Gradle@2
        inputs:
          workingDirectory: ""
          gradleWrapperFile: "gradlew"
          javaHomeOption: "JDKVersion"
          jdkVersionOption: "1.12"
          jdkArchitectureOption: "x64"
          publishJUnitResults: false
          testResultsFiles: "**/TEST-*.xml"
          tasks: "build jlink"
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo hello from Linux
      - task: Gradle@2
        inputs:
          workingDirectory: ""
          gradleWrapperFile: "gradlew"
          javaHomeOption: "JDKVersion"
          jdkVersionOption: "1.12"
          jdkArchitectureOption: "x64"
          publishJUnitResults: false
          testResultsFiles: "**/TEST-*.xml"
          tasks: "build jlink"
  - job: macOS
    pool:
      vmImage: 'macOS-latest'
    steps:
      - script: echo hello from macOS
      - task: Gradle@2
        inputs:
          workingDirectory: ""
          gradleWrapperFile: "gradlew"
          javaHomeOption: "JDKVersion"
          jdkVersionOption: "1.12"
          jdkArchitectureOption: "x64"
          publishJUnitResults: false
          testResultsFiles: "**/TEST-*.xml"
          tasks: "build jlink"